"""empty message

Revision ID: 1cc9bcd660ef
Revises: 24bb54efccde
Create Date: 2022-08-14 01:28:54.941462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc9bcd660ef'
down_revision = '24bb54efccde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_desc', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_desc')
    op.drop_column('Venue', 'seeking')
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
