"""empty message

Revision ID: aa975a2bc15c
Revises: 1cc9bcd660ef
Create Date: 2022-08-14 01:31:44.874644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa975a2bc15c'
down_revision = '1cc9bcd660ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_desc', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_desc')
    op.drop_column('Artist', 'seeking')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
